### ISSUE TITLE
Durandal blog's menu doesn't work (in Chrome, at least).

### ISSUE THREAD

**Issue by JoshMcCullough** [durandalproject/about#3]
I realize this probably doesn't belong here, but I wanted to let you know that the menu on the Durandal blog doesn't seem to work: http://blog.durandal.io

There's an error in the console on-load, and clicking the menu does nothing.

```
embed.js:19 Uncaught TypeError: Cannot read property 'appendChild' of nullm 
    @ embed.js:19n 
    @ embed.js:19h.toJSON 
    @ embed.js:19b.loadEmbed 
    @ embed.js:20(anonymous function) 
    @ embed.js:20
```

**Comment by EisenbergEffect** [comment]
Yes. Indeed. There's something wrong with the blog skin. We plan to re-skin the blog anyway in the not too distant future. The good news is that there isn't anything in that menu I don't think :)

**Comment by JoshMcCullough** [comment]
Thanks Rob. I was trying to determine how to subscribe to the blog -- any pointers there? :)
