### ISSUE TITLE
Skeleton project for Play2 Framework

### ISSUE THREAD

**Issue by suchcto** [durandalproject/about#4]
Hello guys,

Currently I am trying to use play2 framework (http://playframework.com) and aurelia together. Just wondering if you would keen to have skeleton project for Scala/Play2? If so, I will submit pull request for it once I setup the project.

Emily

**Comment by EisenbergEffect** [comment]
@suchcto This sounds very intriguing. We are working on a CLI for creating new Aurelia projects. Perhaps that's a good candidate for where to put this. Can you share a bit what would be involved with the skeleton and what might make it different? We would certainly like to explore options.

**Comment by EisenbergEffect** [comment]
I think we have this tracked on the CLI so closing here.
